image: node:8.11.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install --registry=https://registry.npm.taobao.org
  - npm run clean
  - npm run build
  - npm run deploy
  artifacts:
    paths:
    - public
  only:
  - master