image: node:8.11.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - sudo npm install hexo-cli -g --registry=https://registry.npm.taobao.org
  - sudo npm install --registry=https://registry.npm.taobao.org
  - sudo hexo clean
  - sudo hexo generate
  - sudo hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master